networks:
  default:
    driver: bridge

services:
  Linux-ES-Docker:
    image: quali/es-server:2023.2
    ports:
      - "5093:5093"
    environment:
      - PARAMS="172.22.0.38,admin,admin,ES-Compose"
    hostname: Linux-ES