networks:
  default:
    driver: bridge

services:
  Linux-ES-Docker:
    image: quali/es-server:2023.2
    ports:
      - "5093:5093"
    environment:
      - PARAMS="ip,username,password,name"
    hostname: Linux-ES
